### ISSUE TITLE
Type 'string' cannot be used to index type 'Mock<T, TResult>'.

### ISSUE THREAD

**Issue by codenoid** [kambojajs/kamboja#122]
while running some test,

```
packages/kamboja-testing/src/mock.ts(19,9): error TS2536: Type 'string' cannot be used to index type 'Mock<T, TResult>'.
```

**Comment by ktutnik** [comment]
Thanks for the feedback, this issue has been fixed on the [newest branch](https://github.com/kambojajs/kamboja/blob/e8b595c5e6a7e7aee7cbb1fbd0342b4c451ee795/packages/kamboja-testing/src/mock.ts#L19) 

This issue seems occur when using TypeScript >2.5 (just gusess)

Please confirm if the branch run fine for you

**Comment by ktutnik** [comment]
Master branch merged
[travis OK](https://travis-ci.org/kambojajs/kamboja/builds/276649592)
